var locations = ["USA", "England", "Australia", "Japan", "Brazil"];
console.log(locations);
console.log(locations[2], locations[4], locations[1], locations[3], locations[0]);
console.log(locations);
console.log(locations[0], locations[3], locations[1], locations[4], locations[2]);
console.log(locations);
console.log('\n');
locations = ["Brazil", "Japan", "Australia", "England", "USA"];
console.log(locations);
locations = ["Australia", "Brazil", "England", "Japan", "USA"];
console.log(locations);
locations = ["USA", "Japan", "England", "Brazil", "Australia"];
console.log(locations);
console.log("2");
